<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_confirmResult</name>
   <tag></tag>
   <elementGuidId>ad384315-b95c-4771-be94-1be4b84aa569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'confirmResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#confirmResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You selected Ok&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fedea5b1-22d7-4fe7-a70f-461f1b1dd49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmResult</value>
      <webElementGuid>7e94e9d6-582d-40c3-9dbf-642703f5abb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>fb9139c9-c093-4c21-8fc4-ca61d450c20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>confirmResult</value>
      <webElementGuid>1cfdc865-68cc-4131-a60d-9087f1a0cf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>You selected Ok</value>
      <webElementGuid>75da6883-fcff-49f8-8806-88217309a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3e28261242e92ea80f847c34a4f3fccb</value>
      <webElementGuid>88656094-ce8e-4c6a-b242-645ae049eb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'confirmResult']</value>
      <webElementGuid>3b8b1c33-85c5-47e8-80fb-4c7e03b5da92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'confirmResult']</value>
      <webElementGuid>2c9812f1-f1a1-467a-ad73-3d1609476bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'confirmResult' and (text() = 'confirmResult' or . = 'confirmResult')]</value>
      <webElementGuid>2197f5d4-c0a0-4a89-9434-89728b4274ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
