<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_promptResult</name>
   <tag></tag>
   <elementGuidId>3a6a36d8-c014-4c52-bc8a-a4dbc13d087f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'promptResult']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#promptResult</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;You entered joli&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>50557127-2f02-4b7b-85cc-ddfdc740c51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>promptResult</value>
      <webElementGuid>06ba3828-722e-4034-bfeb-575fb9330a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>fcdec428-9c20-4df2-bf59-753eb80f8702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>promptResult</value>
      <webElementGuid>a3b84f2c-6f1e-48f2-a9bf-bc99408ddb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>You entered joli</value>
      <webElementGuid>c02d5691-ffad-488a-8b88-7be3e2dc5c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2804294f696c0c9f6bf39d8c438478f9</value>
      <webElementGuid>b59859a8-9a19-435f-a727-894df196b9af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'promptResult']</value>
      <webElementGuid>d2ce65e5-a865-4759-9346-db627ee03543</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'promptResult']</value>
      <webElementGuid>7c972b4c-1747-4905-9c54-77b7d139c723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'promptResult' and (text() = 'promptResult' or . = 'promptResult')]</value>
      <webElementGuid>9ec817ee-1389-4bf1-bc54-56b38fa34466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
