<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closeSmallModal</name>
   <tag></tag>
   <elementGuidId>09be23ec-8e2c-409b-a0b9-61d1c176d213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'closeSmallModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closeSmallModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#closeSmallModal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2db02ba6-c06b-4e3a-89be-28936f3bc482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeSmallModal</value>
      <webElementGuid>2ae7711a-b7c7-49da-aecc-4343e9e78274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87a35fe7-6496-43ba-a1d8-73560a2b0855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>d8ddb534-2d0d-4250-aa86-9a995f0935af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>closeSmallModal</value>
      <webElementGuid>6a24d505-0efc-4985-9657-fdf02c42efdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>feb0ef58-2667-40b3-bd18-74a830e9dfe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8627728cb7b998681aa141bce5550f74</value>
      <webElementGuid>f9e4032c-69e5-44b8-8c88-4384050ce1ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'closeSmallModal']</value>
      <webElementGuid>7af55fdf-50bc-4043-ad75-6de70e179110</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'closeSmallModal']</value>
      <webElementGuid>096d0ba6-4315-4f9f-a0b2-e81603745c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeSmallModal' and @type = 'button' and (text() = 'closeSmallModal' or . = 'closeSmallModal')]</value>
      <webElementGuid>09df2c9f-615b-4a03-8156-bbe5a52bb312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
