<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_contentsmartmodal</name>
   <tag></tag>
   <elementGuidId>d178687b-a479-4e18-92ab-38fc18ab0c9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.modal-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;This is a small modal. It has very less content&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef7a296f-3063-4c40-96af-9f367dcc6b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>af51b85f-00d9-4122-817c-e81506528b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a small modal. It has very less cont</value>
      <webElementGuid>34e658d3-3b99-4238-86a4-f6dd5680f5fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>This is a small modal. It has very less content</value>
      <webElementGuid>1f205c61-6eac-4522-b17c-80b785daf1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8bc35cdd2c049dee91c847803f18f64e</value>
      <webElementGuid>c530b1b0-d72c-46e7-a167-9682470d8596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]</value>
      <webElementGuid>1b990913-4d50-4899-af12-1c12f0a646b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' modal-body ')]</value>
      <webElementGuid>bc04a898-7f5f-4535-a867-ccd5e29e0e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This is a small modal. It has very less cont' or . = 'This is a small modal. It has very less cont')]</value>
      <webElementGuid>ce12257b-16f6-4cb8-994c-37619d388020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
