<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_react-select-2-option-0</name>
   <tag></tag>
   <elementGuidId>f8cfdf5c-907c-4d8f-a2e0-6b4f3e5974d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' subjects-auto-complete__option ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.subjects-auto-complete__option</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Maths&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fcff566-b64b-4907-9253-0c92ae0b202c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subjects-auto-complete__option subjects-auto-complete__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>9a59cf24-4baa-4dae-ba0c-2673bef8cb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-0</value>
      <webElementGuid>7fdab8fe-3855-46f8-923e-350ad498b44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>60700e26-2366-4e00-b6a9-c23d4b3cf63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>react-select-2-option-0</value>
      <webElementGuid>ce47865a-7071-48e5-9976-3e4ba1350545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Maths</value>
      <webElementGuid>b6db3242-8da6-4830-af88-8e56563adcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ddcf428f0f3000f0a544611ed8aa86c</value>
      <webElementGuid>d14ad8c8-e10d-4de1-8520-1973366675ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' subjects-auto-complete__option ')]</value>
      <webElementGuid>9060d6d1-bbf5-4836-a519-e047d25572c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' subjects-auto-complete__option ')]</value>
      <webElementGuid>3ac6c69a-9e27-4a8f-9819-891101861f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-0' and (text() = 'react-select-2-option-0' or . = 'react-select-2-option-0')]</value>
      <webElementGuid>9f10f8c3-6456-4c92-bd8e-88e1806e53b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
