<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sports</name>
   <tag></tag>
   <elementGuidId>fdd8a69e-716d-47de-9756-6fe58179338c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'hobbiesWrapper']/*[(name() = 'div') and (position() = 2)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobbiesWrapper > div:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;SportsReadingMusic&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7936a199-b202-4f18-ad54-34e6dec676e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-9 col-sm-12</value>
      <webElementGuid>61774982-b631-47ef-92b9-ffbf91d23c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sports</value>
      <webElementGuid>66dc5540-ed09-45c4-a554-797fa65ee694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Sports
Reading
Music</value>
      <webElementGuid>99419d41-1782-40e3-bb73-8936aea84524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c3f1237d4ef790c4be6c4313a54c7aa9</value>
      <webElementGuid>3c21b417-f99a-4b9c-837d-d7c772379bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']/*[(name() = 'div') and (position() = 2)]</value>
      <webElementGuid>8a9e18f4-d7d6-468b-a0d8-e3514884ea6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']/*[(name() = 'div') and (position() = 2)]</value>
      <webElementGuid>d55b4683-c8b8-457f-96cc-f7fbd03d82c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sports' or . = 'Sports')]</value>
      <webElementGuid>1cbdfc2f-631f-43e3-b38f-5c6233e16e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
