<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sports</name>
   <tag></tag>
   <elementGuidId>b999f583-1343-454f-9e45-5006884f987e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbiesWrapper .form-check:nth-child(1) .form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5e1adf35-3f9c-49f7-b308-590526542c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>hobbies-checkbox-1</value>
      <webElementGuid>b61c8e47-78cf-4ddd-87e9-458c6abc6710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>7c371176-dba6-4989-aa2f-f6271eafcdc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sports</value>
      <webElementGuid>14704190-4310-4807-a754-310cdd73f06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-30cf7dccb9b025876b4b013af8d11bc0</value>
      <webElementGuid>0dc322fd-6691-4e17-b122-9494af7f0bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>3e2c5ca4-2277-450d-a281-d024bca70ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>6b2dc309-2d75-4450-8af0-b444356e9293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Sports' or . = 'Sports')]</value>
      <webElementGuid>be92e3c8-5e42-42d0-b5ea-af5f36c3c97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
