<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Female</name>
   <tag></tag>
   <elementGuidId>b829afea-c04d-4565-805e-e3c4de6d7366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#genterWrapper .form-check:nth-child(2) .form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'genterWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Female&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2d89c52d-5023-44c8-b727-d1f8a8cdc7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gender-radio-2</value>
      <webElementGuid>8399e9d6-f13f-452d-bdd9-968bd37253c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>d06de2ca-5ca9-4c3e-8910-3f97a92aacf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>e0509678-c28e-437d-bb18-5b30adb8c30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f95250ca635f16eba1897772dd5f0a32</value>
      <webElementGuid>9061f826-d1a4-4b05-915f-70384f194b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'genterWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>912076b1-5553-4e37-80e2-10a31287fbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'genterWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 2)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>d390ca1a-2ca6-437b-acc8-d5e6a7cda3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Female' or . = 'Female')]</value>
      <webElementGuid>d5e86e31-0887-4b93-8f5b-f162b4dea2af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
