<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Other</name>
   <tag></tag>
   <elementGuidId>5c6ce9df-6c17-4f6c-a9ca-af0efd7e0a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-inline ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-radio ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-label ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.custom-control.custom-control-inline.custom-radio:nth-child(3) .custom-control-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Other&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e3ae0e79-461d-4591-be08-bdc3f1d96af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gender-radio-3</value>
      <webElementGuid>185f7ca7-b8ba-4d68-b28a-2bac31784cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-label</value>
      <webElementGuid>3614a79e-d1e5-4a9a-9336-46b8ed951791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other</value>
      <webElementGuid>a4ea61b6-2a0f-4bc0-b900-6dd8c21087a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Other</value>
      <webElementGuid>416313dc-2137-4fd3-ba51-6e7c74cbf5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d7d98208b1ce04ac8bba4d22f7f856c2</value>
      <webElementGuid>ed84cd40-7a40-47fb-8036-6c4b8b73fc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-inline ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-radio ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-label ')]</value>
      <webElementGuid>781f687e-ed35-4a70-9a32-76db127e7a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-inline ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-radio ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-label ')]</value>
      <webElementGuid>464cd4e9-5ad9-492d-be86-b6b96665e509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Other' or . = 'Other')]</value>
      <webElementGuid>038cafa8-7ac0-4607-b744-a779338e08a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
