<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_subjects-label</name>
   <tag></tag>
   <elementGuidId>e4d10dfd-f00d-42d2-9c05-2d073213a9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'subjectsWrapper']//*[@id = 'subjects-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#subjectsWrapper #subjects-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Subjects&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>7d386400-686e-4316-b579-9f164e57bd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>b5a48d1d-b314-4b7f-bb48-d096a8e21a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subjects-label</value>
      <webElementGuid>f41b7f79-b309-4239-9db7-e3354517eb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>subjects-label</value>
      <webElementGuid>4ead1745-a6ab-4863-a740-a6192ce37a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Subjects</value>
      <webElementGuid>e03ef447-1960-4a36-88e7-b43afd88091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-beecc5b697e91df3c51e60aeff4bf4ad</value>
      <webElementGuid>59ad20ec-b64c-4c28-b046-b9f640e55007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'subjectsWrapper']//*[@id = 'subjects-label']</value>
      <webElementGuid>bacb40bd-56e6-4fc1-ad6f-0c790bee8155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'subjectsWrapper']//*[@id = 'subjects-label']</value>
      <webElementGuid>93da460b-65fa-420c-a834-f4d230781818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'subjects-label' and (text() = 'subjects-label' or . = 'subjects-label')]</value>
      <webElementGuid>4fbcf05b-dd90-4a0c-a5d1-256167088463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
