<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Music</name>
   <tag></tag>
   <elementGuidId>6db960eb-a154-44fb-b81f-3a05d1507ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hobbiesWrapper .form-check:nth-child(3) .form-check-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Music&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e11720ab-692f-434c-824f-5037179b39c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>hobbies-checkbox-3</value>
      <webElementGuid>a3ed1c0e-ee94-4369-b7c1-3a79ca34b05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>69b42e4f-d8df-4f39-bdff-4626468b0012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Music</value>
      <webElementGuid>50500cae-6849-4c15-90b2-4be2dbf4cec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Music</value>
      <webElementGuid>106ce7cb-d9ae-4bdb-99d7-5db56941a293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-456b643b2f0b6da94e186b379a09e92b</value>
      <webElementGuid>0f6a6626-396b-4727-afbc-68466858805a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>ffa82b6e-1465-4ca5-a1e0-3b03ccb3cf2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'hobbiesWrapper']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>51c17493-4b4d-4701-bae0-c68476c31469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Music' or . = 'Music')]</value>
      <webElementGuid>a9fb9fb2-4294-4e43-90a5-b0e0703169d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-inline ') and contains(concat(' ', normalize-space(@class), ' '), ' custom-checkbox ') and (position() = 3)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' custom-control-label ')]</value>
      <webElementGuid>63e121e5-d9fa-44c4-90dd-a4a1a8bbefc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
